### ISSUE TITLE
Erro com a dependência pytrustnfe 

### ISSUE THREAD

**Issue by Aldo774** [multidadosti-erp/odoo-brasil#8]
![captura de tela de 2016-12-22 11-59-13](https://cloud.githubusercontent.com/assets/15001160/21427924/6f61386c-c83e-11e6-8367-0e1f40cb7ce7.png)

O seguinte erro ocorre quando realizo a atualização do módulo *br_base*. O pacote 'pytrustnfe' está instalado globalmente.
Entretanto, desaparece quando modifico a 'external_dependence' no *__manifest__.py* do *br_base* de 'pytrustnfe.nfe'  para 'pytrustnfe'

**Comment by mstuttgart** [comment]
Solução: faltava instalar a dependência *suds_requests*. O pacote *pytrustnfe* instalado via PyPi não estava instalando essa dependência.
